name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Setup Build environment
        run: |
          export DEBIAN_FRONTEND=noninteractive 
          export TZ=Europe/Paris
          sudo apt-get update
          sudo apt-get install -y software-properties-common python3 python3-pip curl
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          
          sudo apt-get install -y python3.7-venv python3.8-venv python3.9-venv python3.10-venv
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
          export PATH="/$HOME/.poetry/bin:$PATH"
          python3 -m pip install tox

      - name: Run coverage
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          tox -e coverage
